### ISSUE TITLE
Audio Cuts out on iPhone when playing Audiobooks with windows release

### ISSUE THREAD

**Issue by Muck1ng** [stephen/airsonos#92] opened 2015-01-19 14:39 UTC
Hi,

I have a problem, when listening to audiobook after about 2 minutes the audio will cut out but continue to play on the phone, it will then start again but I'll have missed 30 seconds of audio?

No errors in the cmd window. 

Would updating fix this? if so I how i update the windows package? Just download the newer files and replace the existing ones?

**Comment by LongChair** [comment] 2015-01-19 19:43
I am getting the same kind of cuts when casting from itunes on an iPhone to a Play1.
AirSonos is running on my iMac, there is no error log in the airsonos console.

FWIW, same configuration but playing from Sonos app from the iPhone to the same play1 play flawlessly. Playback will cut, seems like the Airplay device disappears ..., and then comes back.

**Comment by Muck1ng** [comment] 2015-02-10 09:08
Any updates on this?  I'd really like to get this working otherwise I'll be selling my play1.

**Comment by stephen** [comment] 2015-02-28 22:41
Will be solved by https://github.com/stephen/airsonos/issues/110. This is a duplicate of #20.

**Closed by stephen** 2015-02-28 22:41 UTC
