### ISSUE TITLE
dns server error

### ISSUE THREAD

**Issue by lateave** [stephen/airsonos#154] opened 2015-04-19 09:40 UTC
Hi Stephen, 

Very interested to get this working, but I seem to be having some problems. While I am able to find AirSonos and the Sonos system there appears to be another issue. Would you have any ideas what I am missing here? 

Thank you again,

Avery

C:\Users\Avery>where airsonos
C:\Users\Avery\AppData\Roaming\npm\airsonos
C:\Users\Avery\AppData\Roaming\npm\airsonos.cmd

C:\Users\Avery>airsonos
Unexpected result while probing for avahi: { [Error: dns service error: unknown
error code] errorCode: -65563 }
Searching for Sonos devices on network...
Setting up AirSonos for Living Room {192.168.0.2:1400}

Error: dns service error: unknown error code
    at new Advertisement (C:\Users\Avery\AppData\Roaming\npm\node_modules\airson
os\node_modules\nodetunes\node_modules\mdns\lib\advertisement.js:56:10)
    at Object.create [as createAdvertisement] (C:\Users\Avery\AppData\Roaming\np
m\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\advertiseme
nt.js:64:10)
    at NodeTunes.<anonymous> (C:\Users\Avery\AppData\Roaming\npm\node_modules\ai
rsonos\node_modules\nodetunes\lib\server.js:65:21)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)

**Comment by stephen** [comment] 2015-08-09 22:48
Duplicate of #143

**Closed by stephen** 2015-08-09 22:48 UTC
